name: MLflow CI

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install -r MLProject/requirements.txt

      - name: Set MLflow Tracking URI
        run: |
          echo "Using local MLflow tracking"

      - name: Install MLflow
        run: |
          pip install mlflow

      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          echo "Training completed successfully"

      - name: Install Python dependencies
        run: |
          pip install mlflow

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts-${{ github.run_number }}
          path: MLProject

      - name: Upload to Google Drive
        run: |
          echo "Artifact backup step"

      - name: Build Docker Model
        run: |
          docker build -t amadeisgenta/telco-churn:latest ./MLProject

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag amadeisgenta/telco-churn:latest amadeisgenta/telco-churn:latest

      - name: Push Docker Image
        run: |
          docker push amadeisgenta/telco-churn:latest
